name: Build go-ul_linux_x86 (Rust version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: i686-unknown-linux-gnu

    - name: Install dependencies for cross-compilation
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib

    - name: Build binary
      run: |
        mkdir -p build
        cargo build --release --target i686-unknown-linux-gnu
        cp target/i686-unknown-linux-gnu/release/go-upload build/go-ul_linux_x86

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-ul_linux_x86
        path: build/go-ul_linux_x86
